// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __sobel_dlog_64ns_6jbC__HH__
#define __sobel_dlog_64ns_6jbC__HH__
#include "ACMP_dlog.h"
#include <systemc>

template<
    int ID,
    int NUM_STAGE,
    int din0_WIDTH,
    int din1_WIDTH,
    int dout_WIDTH>
SC_MODULE(sobel_dlog_64ns_6jbC) {
    sc_core::sc_in_clk clk;
    sc_core::sc_in<sc_dt::sc_logic> reset;
    sc_core::sc_in<sc_dt::sc_logic> ce;
    sc_core::sc_in< sc_dt::sc_lv<din0_WIDTH> >   din0;
    sc_core::sc_in< sc_dt::sc_lv<din1_WIDTH> >   din1;
    sc_core::sc_out< sc_dt::sc_lv<dout_WIDTH> >   dout;



    ACMP_dlog<ID, 31, din0_WIDTH, din1_WIDTH, dout_WIDTH> ACMP_dlog_U;

    SC_CTOR(sobel_dlog_64ns_6jbC):  ACMP_dlog_U ("ACMP_dlog_U") {
        ACMP_dlog_U.clk(clk);
        ACMP_dlog_U.reset(reset);
        ACMP_dlog_U.ce(ce);
        ACMP_dlog_U.din0(din0);
        ACMP_dlog_U.din1(din1);
        ACMP_dlog_U.dout(dout);

    }

};

#endif //
