# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/arm/arm.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arm || ORIG_REF_NAME==arm}]

# IP: bd/arm/ip/arm_processing_system7_0_0/arm_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arm_processing_system7_0_0 || ORIG_REF_NAME==arm_processing_system7_0_0}]

# IP: bd/arm/ip/arm_rst_ps7_0_100M_0/arm_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arm_rst_ps7_0_100M_0 || ORIG_REF_NAME==arm_rst_ps7_0_100M_0}]

# IP: bd/arm/ip/arm_sobel_0_1/arm_sobel_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arm_sobel_0_1 || ORIG_REF_NAME==arm_sobel_0_1}]

# IP: bd/arm/ip/arm_ps7_0_axi_periph_1/arm_ps7_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arm_ps7_0_axi_periph_1 || ORIG_REF_NAME==arm_ps7_0_axi_periph_1}]

# IP: bd/arm/ip/arm_axi_mem_intercon_0/arm_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arm_axi_mem_intercon_0 || ORIG_REF_NAME==arm_axi_mem_intercon_0}]

# IP: bd/arm/ip/arm_xbar_1/arm_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arm_xbar_1 || ORIG_REF_NAME==arm_xbar_1}]

# IP: bd/arm/ip/arm_auto_pc_0/arm_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arm_auto_pc_0 || ORIG_REF_NAME==arm_auto_pc_0}]

# IP: bd/arm/ip/arm_auto_pc_1/arm_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arm_auto_pc_1 || ORIG_REF_NAME==arm_auto_pc_1}]

# IP: bd/arm/ip/arm_auto_us_0/arm_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arm_auto_us_0 || ORIG_REF_NAME==arm_auto_us_0}]

# IP: bd/arm/ip/arm_auto_us_1/arm_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arm_auto_us_1 || ORIG_REF_NAME==arm_auto_us_1}]

# XDC: bd/arm/arm_ooc.xdc
