# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/konto/Documents/embeded/lab2/lab2_simple_arm/lab2_simple_arm.srcs/sources_1/bd/arm/ip/arm_sobel_0_1/arm_sobel_0_1.xci
# IP: The module: 'arm_sobel_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/konto/Documents/embeded/lab2/lab2_simple_arm/lab2_simple_arm.srcs/sources_1/bd/arm/ip/arm_sobel_0_1/constraints/sobel_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'arm_sobel_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: c:/Users/konto/Documents/embeded/lab2/lab2_simple_arm/lab2_simple_arm.srcs/sources_1/bd/arm/ip/arm_sobel_0_1/arm_sobel_0_1.xci
# IP: The module: 'arm_sobel_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/konto/Documents/embeded/lab2/lab2_simple_arm/lab2_simple_arm.srcs/sources_1/bd/arm/ip/arm_sobel_0_1/constraints/sobel_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'arm_sobel_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
