// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module convolution2D (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        posy,
        posx,
        m_axi_input_r_AWVALID,
        m_axi_input_r_AWREADY,
        m_axi_input_r_AWADDR,
        m_axi_input_r_AWID,
        m_axi_input_r_AWLEN,
        m_axi_input_r_AWSIZE,
        m_axi_input_r_AWBURST,
        m_axi_input_r_AWLOCK,
        m_axi_input_r_AWCACHE,
        m_axi_input_r_AWPROT,
        m_axi_input_r_AWQOS,
        m_axi_input_r_AWREGION,
        m_axi_input_r_AWUSER,
        m_axi_input_r_WVALID,
        m_axi_input_r_WREADY,
        m_axi_input_r_WDATA,
        m_axi_input_r_WSTRB,
        m_axi_input_r_WLAST,
        m_axi_input_r_WID,
        m_axi_input_r_WUSER,
        m_axi_input_r_ARVALID,
        m_axi_input_r_ARREADY,
        m_axi_input_r_ARADDR,
        m_axi_input_r_ARID,
        m_axi_input_r_ARLEN,
        m_axi_input_r_ARSIZE,
        m_axi_input_r_ARBURST,
        m_axi_input_r_ARLOCK,
        m_axi_input_r_ARCACHE,
        m_axi_input_r_ARPROT,
        m_axi_input_r_ARQOS,
        m_axi_input_r_ARREGION,
        m_axi_input_r_ARUSER,
        m_axi_input_r_RVALID,
        m_axi_input_r_RREADY,
        m_axi_input_r_RDATA,
        m_axi_input_r_RLAST,
        m_axi_input_r_RID,
        m_axi_input_r_RUSER,
        m_axi_input_r_RRESP,
        m_axi_input_r_BVALID,
        m_axi_input_r_BREADY,
        m_axi_input_r_BRESP,
        m_axi_input_r_BID,
        m_axi_input_r_BUSER,
        input1,
        operator_address0,
        operator_ce0,
        operator_q0,
        ap_return
);

parameter    ap_ST_fsm_state1 = 15'b1;
parameter    ap_ST_fsm_state2 = 15'b10;
parameter    ap_ST_fsm_state3 = 15'b100;
parameter    ap_ST_fsm_state4 = 15'b1000;
parameter    ap_ST_fsm_state5 = 15'b10000;
parameter    ap_ST_fsm_state6 = 15'b100000;
parameter    ap_ST_fsm_state7 = 15'b1000000;
parameter    ap_ST_fsm_state8 = 15'b10000000;
parameter    ap_ST_fsm_state9 = 15'b100000000;
parameter    ap_ST_fsm_state10 = 15'b1000000000;
parameter    ap_ST_fsm_state11 = 15'b10000000000;
parameter    ap_ST_fsm_state12 = 15'b100000000000;
parameter    ap_ST_fsm_state13 = 15'b1000000000000;
parameter    ap_ST_fsm_state14 = 15'b10000000000000;
parameter    ap_ST_fsm_state15 = 15'b100000000000000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv3_0 = 3'b000;
parameter    ap_const_lv2_0 = 2'b00;
parameter    ap_const_lv4_0 = 4'b0000;
parameter    ap_const_lv8_0 = 8'b00000000;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv32_A = 32'b1010;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv32_B = 32'b1011;
parameter    ap_const_lv32_D = 32'b1101;
parameter    ap_const_lv3_7 = 3'b111;
parameter    ap_const_lv32_E = 32'b1110;
parameter    ap_const_lv3_2 = 3'b10;
parameter    ap_const_lv3_1 = 3'b1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [9:0] posy;
input  [9:0] posx;
output   m_axi_input_r_AWVALID;
input   m_axi_input_r_AWREADY;
output  [31:0] m_axi_input_r_AWADDR;
output  [0:0] m_axi_input_r_AWID;
output  [31:0] m_axi_input_r_AWLEN;
output  [2:0] m_axi_input_r_AWSIZE;
output  [1:0] m_axi_input_r_AWBURST;
output  [1:0] m_axi_input_r_AWLOCK;
output  [3:0] m_axi_input_r_AWCACHE;
output  [2:0] m_axi_input_r_AWPROT;
output  [3:0] m_axi_input_r_AWQOS;
output  [3:0] m_axi_input_r_AWREGION;
output  [0:0] m_axi_input_r_AWUSER;
output   m_axi_input_r_WVALID;
input   m_axi_input_r_WREADY;
output  [7:0] m_axi_input_r_WDATA;
output  [0:0] m_axi_input_r_WSTRB;
output   m_axi_input_r_WLAST;
output  [0:0] m_axi_input_r_WID;
output  [0:0] m_axi_input_r_WUSER;
output   m_axi_input_r_ARVALID;
input   m_axi_input_r_ARREADY;
output  [31:0] m_axi_input_r_ARADDR;
output  [0:0] m_axi_input_r_ARID;
output  [31:0] m_axi_input_r_ARLEN;
output  [2:0] m_axi_input_r_ARSIZE;
output  [1:0] m_axi_input_r_ARBURST;
output  [1:0] m_axi_input_r_ARLOCK;
output  [3:0] m_axi_input_r_ARCACHE;
output  [2:0] m_axi_input_r_ARPROT;
output  [3:0] m_axi_input_r_ARQOS;
output  [3:0] m_axi_input_r_ARREGION;
output  [0:0] m_axi_input_r_ARUSER;
input   m_axi_input_r_RVALID;
output   m_axi_input_r_RREADY;
input  [7:0] m_axi_input_r_RDATA;
input   m_axi_input_r_RLAST;
input  [0:0] m_axi_input_r_RID;
input  [0:0] m_axi_input_r_RUSER;
input  [1:0] m_axi_input_r_RRESP;
input   m_axi_input_r_BVALID;
output   m_axi_input_r_BREADY;
input  [1:0] m_axi_input_r_BRESP;
input  [0:0] m_axi_input_r_BID;
input  [0:0] m_axi_input_r_BUSER;
input  [31:0] input1;
output  [3:0] operator_address0;
output   operator_ce0;
input  [31:0] operator_q0;
output  [31:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg m_axi_input_r_ARVALID;
reg m_axi_input_r_RREADY;
reg operator_ce0;

(* fsm_encoding = "none" *) reg   [14:0] ap_CS_fsm;
wire   [0:0] ap_CS_fsm_state1;
reg    input_r_blk_n_AR;
wire   [0:0] ap_CS_fsm_state4;
reg    input_r_blk_n_R;
wire   [0:0] ap_CS_fsm_state11;
wire   [2:0] j_2_fu_135_p2;
reg   [2:0] j_2_reg_273;
wire   [0:0] ap_CS_fsm_state2;
wire   [0:0] exitcond1_fu_129_p2;
wire   [4:0] j_2_cast_fu_141_p1;
reg   [4:0] j_2_cast_reg_278;
reg   [31:0] input_addr_reg_286;
wire   [0:0] ap_CS_fsm_state3;
wire   [0:0] exitcond_fu_145_p2;
wire   [2:0] i_2_fu_196_p2;
reg   [2:0] i_2_reg_292;
wire   [4:0] tmp_1_fu_220_p2;
reg   [4:0] tmp_1_reg_297;
reg   [7:0] input_addr_read_reg_302;
wire   [0:0] ap_CS_fsm_state12;
wire   [31:0] grp_fu_232_p2;
reg   [31:0] tmp_4_reg_322;
wire   [0:0] ap_CS_fsm_state14;
reg   [2:0] j_reg_98;
reg   [2:0] i_reg_110;
wire   [0:0] ap_CS_fsm_state15;
wire   [31:0] tmp_11_cast_fu_225_p1;
wire   [31:0] sum1_fu_185_p2;
reg    ap_reg_ioackin_m_axi_input_r_ARREADY;
reg    ap_sig_ioackin_m_axi_input_r_ARREADY;
reg   [31:0] res_fu_52;
wire   [31:0] res_1_fu_238_p2;
wire  signed [9:0] tmp_2_cast_fu_151_p1;
wire   [9:0] tmp5_fu_155_p2;
wire   [19:0] tmp1_fu_160_p3;
wire  signed [21:0] j_cast7_fu_171_p1;
wire   [21:0] tmp1_cast_fu_167_p1;
wire   [21:0] sum_fu_175_p2;
wire   [31:0] sum_cast_fu_181_p1;
wire   [4:0] tmp_fu_206_p3;
wire   [4:0] i_2_cast_cast_fu_202_p1;
wire   [4:0] tmp_s_fu_214_p2;
wire   [7:0] grp_fu_232_p0;
reg   [14:0] ap_NS_fsm;
wire   [31:0] grp_fu_232_p00;

// power-on initialization
initial begin
#0 ap_CS_fsm = 15'b1;
#0 ap_reg_ioackin_m_axi_input_r_ARREADY = 1'b0;
end

sobel_mul_8ns_32sbkb #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
sobel_mul_8ns_32sbkb_U0(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_232_p0),
    .din1(operator_q0),
    .ce(1'b1),
    .dout(grp_fu_232_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ioackin_m_axi_input_r_ARREADY <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            if (~(1'b0 == ap_sig_ioackin_m_axi_input_r_ARREADY)) begin
                ap_reg_ioackin_m_axi_input_r_ARREADY <= 1'b0;
            end else if ((1'b1 == m_axi_input_r_ARREADY)) begin
                ap_reg_ioackin_m_axi_input_r_ARREADY <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == exitcond1_fu_129_p2))) begin
        i_reg_110 <= ap_const_lv3_7;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        i_reg_110 <= i_2_reg_292;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & ~(1'b0 == exitcond_fu_145_p2))) begin
        j_reg_98 <= j_2_reg_273;
    end else if (((ap_CS_fsm_state1 == 1'b1) & ~(ap_start == 1'b0))) begin
        j_reg_98 <= ap_const_lv3_7;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        res_fu_52 <= res_1_fu_238_p2;
    end else if (((ap_CS_fsm_state1 == 1'b1) & ~(ap_start == 1'b0))) begin
        res_fu_52 <= ap_const_lv32_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (1'b0 == exitcond_fu_145_p2))) begin
        i_2_reg_292 <= i_2_fu_196_p2;
        input_addr_reg_286 <= sum1_fu_185_p2;
        tmp_1_reg_297 <= tmp_1_fu_220_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state11) & ~(m_axi_input_r_RVALID == 1'b0))) begin
        input_addr_read_reg_302 <= m_axi_input_r_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == exitcond1_fu_129_p2))) begin
        j_2_cast_reg_278[2 : 0] <= j_2_cast_fu_141_p1[2 : 0];
        j_2_reg_273 <= j_2_fu_135_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        tmp_4_reg_322 <= grp_fu_232_p2;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_start) & (ap_CS_fsm_state1 == 1'b1)) | ((1'b1 == ap_CS_fsm_state2) & ~(1'b0 == exitcond1_fu_129_p2)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (ap_CS_fsm_state1 == 1'b1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & ~(1'b0 == exitcond1_fu_129_p2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_reg_ioackin_m_axi_input_r_ARREADY)) begin
        ap_sig_ioackin_m_axi_input_r_ARREADY = m_axi_input_r_ARREADY;
    end else begin
        ap_sig_ioackin_m_axi_input_r_ARREADY = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        input_r_blk_n_AR = m_axi_input_r_ARREADY;
    end else begin
        input_r_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        input_r_blk_n_R = m_axi_input_r_RVALID;
    end else begin
        input_r_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (1'b0 == ap_reg_ioackin_m_axi_input_r_ARREADY))) begin
        m_axi_input_r_ARVALID = 1'b1;
    end else begin
        m_axi_input_r_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) & ~(m_axi_input_r_RVALID == 1'b0))) begin
        m_axi_input_r_RREADY = 1'b1;
    end else begin
        m_axi_input_r_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) & ~(m_axi_input_r_RVALID == 1'b0))) begin
        operator_ce0 = 1'b1;
    end else begin
        operator_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (~(ap_start == 1'b0)) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (~(1'b0 == exitcond1_fu_129_p2)) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (~(1'b0 == exitcond_fu_145_p2)) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (~(1'b0 == ap_sig_ioackin_m_axi_input_r_ARREADY)) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            if (~(m_axi_input_r_RVALID == 1'b0)) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[ap_const_lv32_0];

assign ap_CS_fsm_state11 = ap_CS_fsm[ap_const_lv32_A];

assign ap_CS_fsm_state12 = ap_CS_fsm[ap_const_lv32_B];

assign ap_CS_fsm_state14 = ap_CS_fsm[ap_const_lv32_D];

assign ap_CS_fsm_state15 = ap_CS_fsm[ap_const_lv32_E];

assign ap_CS_fsm_state2 = ap_CS_fsm[ap_const_lv32_1];

assign ap_CS_fsm_state3 = ap_CS_fsm[ap_const_lv32_2];

assign ap_CS_fsm_state4 = ap_CS_fsm[ap_const_lv32_3];

assign ap_return = res_fu_52;

assign exitcond1_fu_129_p2 = ((j_reg_98 == ap_const_lv3_2) ? 1'b1 : 1'b0);

assign exitcond_fu_145_p2 = ((i_reg_110 == ap_const_lv3_2) ? 1'b1 : 1'b0);

assign grp_fu_232_p0 = grp_fu_232_p00;

assign grp_fu_232_p00 = input_addr_read_reg_302;

assign i_2_cast_cast_fu_202_p1 = i_2_fu_196_p2;

assign i_2_fu_196_p2 = (i_reg_110 + ap_const_lv3_1);

assign j_2_cast_fu_141_p1 = j_2_fu_135_p2;

assign j_2_fu_135_p2 = (j_reg_98 + ap_const_lv3_1);

assign j_cast7_fu_171_p1 = $signed(j_reg_98);

assign m_axi_input_r_ARADDR = input_addr_reg_286;

assign m_axi_input_r_ARBURST = ap_const_lv2_0;

assign m_axi_input_r_ARCACHE = ap_const_lv4_0;

assign m_axi_input_r_ARID = 1'b0;

assign m_axi_input_r_ARLEN = ap_const_lv32_1;

assign m_axi_input_r_ARLOCK = ap_const_lv2_0;

assign m_axi_input_r_ARPROT = ap_const_lv3_0;

assign m_axi_input_r_ARQOS = ap_const_lv4_0;

assign m_axi_input_r_ARREGION = ap_const_lv4_0;

assign m_axi_input_r_ARSIZE = ap_const_lv3_0;

assign m_axi_input_r_ARUSER = 1'b0;

assign m_axi_input_r_AWADDR = ap_const_lv32_0;

assign m_axi_input_r_AWBURST = ap_const_lv2_0;

assign m_axi_input_r_AWCACHE = ap_const_lv4_0;

assign m_axi_input_r_AWID = 1'b0;

assign m_axi_input_r_AWLEN = ap_const_lv32_0;

assign m_axi_input_r_AWLOCK = ap_const_lv2_0;

assign m_axi_input_r_AWPROT = ap_const_lv3_0;

assign m_axi_input_r_AWQOS = ap_const_lv4_0;

assign m_axi_input_r_AWREGION = ap_const_lv4_0;

assign m_axi_input_r_AWSIZE = ap_const_lv3_0;

assign m_axi_input_r_AWUSER = 1'b0;

assign m_axi_input_r_AWVALID = 1'b0;

assign m_axi_input_r_BREADY = 1'b0;

assign m_axi_input_r_WDATA = ap_const_lv8_0;

assign m_axi_input_r_WID = 1'b0;

assign m_axi_input_r_WLAST = 1'b0;

assign m_axi_input_r_WSTRB = 1'b0;

assign m_axi_input_r_WUSER = 1'b0;

assign m_axi_input_r_WVALID = 1'b0;

assign operator_address0 = tmp_11_cast_fu_225_p1;

assign res_1_fu_238_p2 = (res_fu_52 + tmp_4_reg_322);

assign sum1_fu_185_p2 = (input1 + sum_cast_fu_181_p1);

assign sum_cast_fu_181_p1 = sum_fu_175_p2;

assign sum_fu_175_p2 = ($signed(j_cast7_fu_171_p1) + $signed(tmp1_cast_fu_167_p1));

assign tmp1_cast_fu_167_p1 = tmp1_fu_160_p3;

assign tmp1_fu_160_p3 = {{tmp5_fu_155_p2}, {posx}};

assign tmp5_fu_155_p2 = ($signed(posy) + $signed(tmp_2_cast_fu_151_p1));

assign tmp_11_cast_fu_225_p1 = tmp_1_reg_297;

assign tmp_1_fu_220_p2 = (tmp_s_fu_214_p2 + j_2_cast_reg_278);

assign tmp_2_cast_fu_151_p1 = $signed(i_reg_110);

assign tmp_fu_206_p3 = {{i_2_fu_196_p2}, {ap_const_lv2_0}};

assign tmp_s_fu_214_p2 = (tmp_fu_206_p3 - i_2_cast_cast_fu_202_p1);

always @ (posedge ap_clk) begin
    j_2_cast_reg_278[4:3] <= 2'b00;
end

endmodule //convolution2D
